In [ ]:
a1=[1,2,3]
a2=[4,5,6]
sum_r=[]
for i in range(len(a1)):
  sum_r.append(a1[i]+a2[i])
print(sum_r)

[5, 7, 9]


In [ ]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([1])
print(np.add(a1,a2))

[2 3 4]


In [ ]:
#Problem1
#Qn1
import numpy as np
empty_array = np.zeros((2,2))
print(empty_array)

[[0. 0.]
 [0. 0.]]


In [ ]:
#Qn2
import numpy as np
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Qn3
import numpy as np
array = np.full((2,3), 5)
print(array)

[[5 5 5]
 [5 5 5]]


In [ ]:
#Qn4
import numpy as np
#Example array
array = np.array([[2, 2], [3, 3]])

#New array of zeros with same shape and size as example array
zeroArray = np.zeros_like(array)
print(zeroArray)

[[0 0]
 [0 0]]


In [ ]:
#Qn5
import numpy as np
#Example array
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#New array of ones with same shape and size as example array
onesArray = np.ones_like(arr1)
print(onesArray)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#Qn6
import numpy as np

new_list = [1, 2, 3, 4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


In [ ]:
#Problem2
#Qn1
import numpy as np

#use of arange allows to print from 10 to 49 and doesnot include 50
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Qn2
import numpy as np

#Create array from 0 to 8
arr1 = np.arange(9)

#reshape the arr1 into matrix
matrix = arr1.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Qn3
import numpy as np

#use np.eye to create identity matrix of any shape and size
identity_matrix = np.eye(3, 3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Qn4
import numpy as np

#Create a random array of size 30
arr1 = np.random.rand(30)

#Calculate its mean with arr1.mean()
array_mean = arr1.mean()

print("Random array is: ", arr1)
print("Mean of random array is: ", array_mean)

Random array is:  [0.5663371  0.11146332 0.94457831 0.22392722 0.97263039 0.59098595
 0.34511539 0.18835994 0.50170205 0.42327948 0.00194756 0.43031754
 0.42629248 0.63654238 0.20707779 0.06245691 0.98239914 0.87053758
 0.10717216 0.99915784 0.90442876 0.5091899  0.66336604 0.22429271
 0.78774079 0.40981912 0.49235484 0.55307797 0.53422835 0.40279056]
Mean of random array is:  0.5024523195728615


In [ ]:
#Qn5
import numpy as np

#create random array of size 10x10
array = np.random.rand(10, 10)

#find minimum and maximum value
min_value = array.min()
max_value = array.max()

print("Random array: ", array)
print("Minimum value: ", min_value)
print("Maximum value: ", max_value)

Random array:  [[0.56847933 0.57755631 0.15797382 0.69109491 0.66604642 0.29030182
  0.90104132 0.47398556 0.82851092 0.64443294]
 [0.24411167 0.29666533 0.64361246 0.97174686 0.67229028 0.16585819
  0.30206409 0.0878045  0.07003089 0.78921999]
 [0.23052567 0.13650708 0.29321987 0.13908277 0.3810635  0.22470511
  0.51494917 0.42902817 0.23997323 0.23080957]
 [0.1761829  0.79814843 0.15192205 0.68358882 0.17184641 0.78512598
  0.84086526 0.37836959 0.52208961 0.64793257]
 [0.86525812 0.08731466 0.73585846 0.79579737 0.29222537 0.17013183
  0.36070516 0.36723494 0.06202901 0.85198149]
 [0.75368913 0.12432508 0.44493926 0.08181737 0.56228355 0.01775664
  0.98812408 0.64781388 0.22731702 0.49584184]
 [0.35413988 0.59915466 0.23390023 0.46186821 0.23934067 0.81202164
  0.6768718  0.34429789 0.05183872 0.4772049 ]
 [0.65233073 0.08055135 0.61764583 0.26518193 0.29378385 0.68160736
  0.35560195 0.61465362 0.29468818 0.34669426]
 [0.11980231 0.70381252 0.55581385 0.79281513 0.54664748 0.320573

In [ ]:
#Qn6
import numpy as np

#create zero array of 10x10
zero_array = np.zeros((10, 10))

#replace 5th element by 1
#0=1st row and 4=5th column
zero_array[0, 4] = 1

print("Zero array: ")
print(zero_array)

Zero array: 
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#Qn7
import numpy as np

arr = [1,2,0,0,4,0]

#slicing method to reverse array: -1 means starting from end to start
reversed_array = arr[::-1]

print("Given array: ",arr)
print("Reversed array: ",reversed_array)

Given array:  [1, 2, 0, 0, 4, 0]
Reversed array:  [0, 4, 0, 0, 2, 1]


In [ ]:
#Qn8
import numpy as np

arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Qn9
import numpy as np
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Problem3
#Qn1
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

array_Sum = np.add(x,y)
print("x:\n", x)
print("y:\n", y)

print("Sum of x and y:\n",array_Sum)

x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
Sum of x and y:
 [[ 6  8]
 [10 13]]


In [ ]:
#Qn2
import numpy as np

v = np.array([9,10])
w = np.array([11,12])

array_sub = np.subtract(v, w)

print("v:", v)
print("w:", w)

print("Difference of v and w:\n",array_sub)

v: [ 9 10]
w: [11 12]
Difference of v and w:
 [-2 -2]


In [ ]:
#Qn3
import numpy as np

#multiplying by an integer:3 to array x
arr = 3*x

print("x:\n",x)
print("After multiplying by 3:\n", arr)

x:
 [[1 2]
 [3 5]]
After multiplying by 3:
 [[ 3  6]
 [ 9 15]]


In [ ]:
#Qn4
import numpy as np

#square each element of array v
sq_array = np.square(v)

print("v:",v)
print("Square of v:",sq_array)

v: [ 9 10]
Square of v: [ 81 100]


In [ ]:
#Qn5
import numpy as np

#dot product between v(and)w
dot1 = np.dot(v,w)

#dot product between x(and)v
dot2 = np.dot(x,v)

#dot product between x(and)y
dot3 = np.dot(x,y)

print("Dot product between v(and)w:",dot1)
print("Dot product between x(and)v:",dot2)
print("Dot product between x(and)y:\n",dot3)

Dot product between v(and)w: 219
Dot product between x(and)v: [29 77]
Dot product between x(and)y:
 [[19 22]
 [50 58]]


In [ ]:
#Qn6
import numpy as np

#concatenate x and y along row with axis=1
con1 = np.concatenate((x,y), axis=0)

#concatenate v and w along column using hstack()
stack1 = np.vstack((v,w))

print("Concatenate x and y along row:\n",con1)
print("Concatenate v and w along column:",stack1)

Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column: [[ 9 10]
 [11 12]]


In [ ]:
#Qn7
import numpy as np

#Concatenate x and v

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
print(concat_xv_error)



all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
#Problem4
#Qn1
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

#Inverse of matrix A
A_inverse = np.linalg.inv(A)
#Product of A and A inverse
result = np.dot(A, A_inverse)
identity_matrix = np.eye(2)

print("Matrix A:\n",A)
print("Inverse of matrix A:\n",A_inverse)
print("A*A^-1:\n",result)
print("Identity matrix:\n",identity_matrix)

Matrix A:
 [[3 4]
 [7 8]]
Inverse of matrix A:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A*A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix:
 [[1. 0.]
 [0. 1.]]


In [ ]:
#Qn2
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n",AB)
print("BA:\n",BA)
print(np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
False


In [ ]:
#Qn3
import numpy as np

AB = np.dot(A, B)
AB_T = np.transpose(AB)

B_T = np.transpose(B)
A_T = np.transpose(A)
BT_AT = np.dot(B_T, A_T)

print("Matrix (AB)^T:\n",AB_T)
print("Matrix B^T*A^T:\n",BT_AT)
print(np.array_equal(AB_T, BT_AT))

Matrix (AB)^T:
 [[23 51]
 [13 29]]
Matrix B^T*A^T:
 [[23 51]
 [13 29]]
True


In [ ]:
#Linear equation
import numpy as np

#The given equation in matrix form is
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

#For AX=B, X=A^-1.B so,
A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)

print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("Solution of AX=B:\n", X)
print("Hence,")
print("x=",X[0])
print("y=",X[1])
print("z=",X[2])


Matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Matrix B:
 [-1 -3  9]
Solution of AX=B:
 [ 2.  1. -2.]
Hence,
x= 2.0
y= 1.0
z= -2.0
